name: "RabbitMQ"
description: "Rabbit message queue"
version: "3.10.5"
slug: "rabbitmq"
init: true
ingress: true
ingress_port: 0
ingress_stream: true
ports:
  80/tcp: 15672
ports_description:
  80/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386